version: 2

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job3
                                     
workflows:
  version: 2
  papa:
    jobs:
      - premier

  tata:
    jobs:
      - deuxieme
      
  lala:
    jobs:
      - troisieme
