version: 2

jobs:
  codecoverage:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo codecoverage
                   echo "passing secret"
                   echo 'export {SHARE_ENV}' >> $BASH_ENV
                   echo ${SHARE_ENV}
                   echo $SHARE_ENV
